config/routes.rb
Rails.application.routes.draw do

  get 'records/new'
  root 'users#top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'admin' => 'users#admin'
  delete 'all_destroy' => 'users#all_destroy'
  resources :users
  resources :folders, shallow: true do
    resources :codes
  end
  resources :spans

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  belongs_to :folder

  validates :name, presence: true
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :codes, dependent: :destroy


  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
end

app/models/span.rb
class Span < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :folders, dependent: :destroy
  has_many :records, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :authenticate_user
  before_action :correct_user, only: %i[edit update]

  def new
    @code = Code.new
  end

  def create
    @code = Code.new(code_params)
    @code.line = @code.content.lines.count
    @code.folder_id = params[:folder_id]
    if @code.save
      records = Record.where(user_id: current_user.id, day: Date.today)
      if records.empty?
        if Record.where(user_id: current_user.id).empty?
          record = Record.new(user_id: current_user.id, day: Date.today, t_line: 0)
        else
          record = Record.new(user_id: current_user.id, day: Date.today, t_line: Record.where(user_id: current_user.id, day: Date.yesterday).first.t_line)
        end
      else
        record = records.first
      end
      record.t_line += @code.line
      record.save
      redirect_to folder_path(@code.folder_id)
    else
      render :new
    end
  end

  def show
    @code = Code.find(params[:id])
  end

  def edit
    @code = Code.find(params[:id])
  end

  def update
    code = Code.find(params[:id])
    old_line = code.line
    if code.update(code_params)
      code.line = code.content.lines.count
      code.save
      records = Record.where(user_id: current_user.id, created_at: Date.today.in_time_zone.all_day)
      if records.empty?
        if Record.where(user_id: current_user.id).empty?
          record = Record.new(user_id: current_user.id, t_line: 0)
        else
          record = Record.new(user_id: current_user.id, t_line: Record.where(user_id: current_user.id, created_at: Date.yesterday.in_time_zone.all_day).first.t_line)
        end
      else
        record = records.first
      end
      record.t_line += (code.line - old_line)
      record.save
      redirect_to code_path(code)
    else
      render :edit
    end
  end





  private

  def code_params
    params.require(:code).permit(:name, :content)
  end

  def correct_user
    code = Code.find(params[:id])
    return if code.folder.user == current_user

    redirect_to root_path, danger: "アカウントが違います"
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    @folder.user_id = current_user.id
    if @folder.save
      redirect_to current_user
    else
      render :new
    end
  end

  def show
    @folder = Folder.find(params[:id])
    @codes = Code.where(folder_id: @folder.id)
  end







  private

  def folder_params
    params.require(:folder).permit(:name)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      log_in user
      if user.admin == true
        redirect_to "/admin"
      else
        redirect_to user, success: "ログイン成功！"
      end
    else
      redirect_to login_path, danger: "ID／パスワードが違います"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/spans_controller.rb
class SpansController < ApplicationController
  def new
    @span = Span.new
  end

  def create
    @span = Span.new(span_params)
    if @span.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def destroy
    Span.first.destroy
    redirect_to admin_path
  end


  private
    def span_params
      params.require(:span).permit(:start_date, :end_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[show index]
  /before_action :correct_user, only: %i[edit update]/

  def top

    unless Span.all.empty?
      s_day = Span.first.start_date
      e_day = Span.first.end_date
      @span = []
      (s_day..e_day).each do |date|
        @span.push(date)
      end
      # if Record.where(user_id: current_user.id, day: s_day).empty?
      #     start_record = Record.new(user_id: current_user.id, day: s_day, t_line: 0)
      #     start_record.save
      # end

      User.all.each do |user|
        if Record.where(user_id: user.id, day: s_day).empty?
          a = Record.new(user_id: user.id, day: s_day, t_line: 0)
          a.save
        end
        (s_day..Date.today).each do |d|
          if Record.where(user_id: user.id, day: d).empty?
              a = Record.new(user_id: user.id, day: d, t_line: Record.find_by(user_id: user.id, day: d.yesterday).t_line)
              a.save
            end
          end
        end



      @users_line = []
      User.all.each do |user|
        user_line = []
        Record.where(user_id: user.id, day: s_day..e_day).order(day: "asc").each do |r|
          user_line.push(r.t_line)
        end
        @users_line.push(user_line)
      end
      @chart = LazyHighCharts::HighChart.new("graph") do |c|
        c.xAxis(categories: @span)
        c.yAxis(title: {text: "行数"})
        User.all.each_with_index() do |user, i|
        c.series(name: user.name, data: @users_line[i])
        end
      end
    end

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = "pass"
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @folders = @user.folders
  end

  def admin

  end

  def destroy
    span = Span.first
    span.destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end

  def all_destroy
    users = User.all
    users.each do |user|
      unless user.admin
        user.destroy
      end
    end
    redirect_to admin_path, success: "初期化完了！"
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def correct_user
    user = User.find(params[:id])
    return if user == current_user

    redirect_to root_path, danger: "アカウントが違います"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def inform_validation_error(obj)
    html_text = ''
    obj.errors.full_messages.each do |message|
      html_text += content_tag(:div, class: 'alert alert-danger') do
        content_tag(:a, 'x', data: { dismiss: 'alert' })
        message
      end
    end
    raw(html_text)
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate_user

    if current_user == nil

      redirect_to root_path, danger: "ログインしろ"

    end
  end
end

app/helpers/spans_helper.rb
module SpansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/codes/edit.html.slim
h1 コード編集

= form_with model: @code, url: code_path(params[:id]) do |f|
  = f.label :name
  = f.text_field :name, class: "form-control"
  = f.label :content
  = f.text_area :content, style: "width:600px; height:100px", class: "form-control"
  = f.submit class: "btn btn-primary"

app/views/codes/new.html.slim
h1 new Code

= form_with model: @code, url: folder_codes_path(folder_id: params[:folder_id]), local: true do |f|
  = inform_validation_error @code
  = f.label :name
  = f.text_field :name, class: "form-control"
  = f.label :content
  = f.text_area :content, style: "width:600px; height:100px", class: "form-control"
  = f.submit class: "btn btn-primary"

app/views/codes/show.html.slim
h1 = @code.name

= link_to "戻る", folder_path(@code.folder_id)
ul.nav.justify-content-end
  - if current_user.id == @code.folder.user_id
    li.nav-item
      = link_to "コード編集", edit_code_path(@code.id), class: "btn btn-success nav-link"

div style="background-color: whitesmoke; padding: 10px"
  pre
    |
    code  = @code.content

app/views/folders/new.html.slim
h1 新規フォルダ

= form_with model: @folder, local: true do |f|
  = inform_validation_error @folder
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/folders/show.html.slim
h1 = @folder.name

= link_to "戻る", user_path(@folder.user_id)
ul.nav.justify-content-end
  - if current_user.id == @folder.user_id
    li.nav-item
      = link_to "新規コード", new_folder_code_path(params[:id]), class: "btn btn-success nav-link"

table.table.table-hover
  thead
    tr
      th コード名
      th 行数

  tbody
    - @codes.each do |code|
     tr
      td = link_to code.name, code
      td = code.line

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-sm.navbar-dark.bg-dark.mt-3.mb-3
  button.navbar-toggler aria-controls="navbarNav4" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNav4" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  .container
    = link_to '1day 100lines', root_path, class: 'navbar-brand', title: "topへ", rel: "tooltip"
    .collapse.navbar-collapse.justify-content-end
      ul.navbar-nav
        - if logged_in?
          -if current_user.admin == true
            li.nav-item
              = link_to "管理者ツール", admin_path, class: "nav-link"
          li.nav-item
            = link_to "ユーザー一覧", users_path, class: "nav-link"
          li.nav-item
            = link_to current_user.name, user_path(id: current_user), class: "nav-link"
            li.nav-item
              a.nav-link data-method="delete" href="/logout"
                i.fas.fa-sign-out-alt logout
        - else
          li.nav-item
            a.nav-link href="/login"
              i.fas.fa-sign-in-alt login

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | OnedayLines
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'layouts/header'
    - flash.each do |name, msg|
      div class=("alert alert-#{name}")
        = msg.html_safe
    .container
      = yield

app/views/records/new.html.slim
h1 Records#new
p Find me in app/views/records/new.html.slim

app/views/spans/new.html.erb
<h1>Spans#new</h1>
<p>Find me in app/views/spans/new.html.erb</p>

app/views/spans/new.html.slim
h1 期間設定

= form_with model: @span do |f|
  = f.label :start_date
  = f.date_field :start_date
  = f.label :end_date
  = f.date_field :end_date
  = f.submit

app/views/users/admin.html.slim
h1 管理者ツール

= link_to "新規ユーザー作成", new_user_path, class: "btn btn-success"
br
br
- if Span.all.empty?
  = link_to "期間設定", new_span_path, class: "btn btn-info"
  br
  br
- else
  = link_to "期間リセット", span_path(1), method: :delete, class: "btn btn-danger"
  br
  br
= link_to "初期化", all_destroy_path, method: :delete, class: "btn btn-danger"

app/views/users/index.html.slim
h1 ユーザー一覧
table.table
  thead
    tr
      th ユーザー
  tbody
    - @users.each do |user|
      tr
        td
          = link_to(user.name,  user_path(id: user.id))
        td
          - if current_user.admin && user.admin == false
            = link_to("削除", user, method: :delete, data: \
              { confirm: "削除しますか？",
              cansel: "やめる",
              commit: "消す"}, title: "確認")

app/views/users/new.html.slim
h1 新規登録

= form_with model: @user, local: true do |f|
  = inform_validation_error @user
  = f.label :name
  = f.text_field :name, class: "form-control"
  = f.submit

app/views/users/show.html.slim
h1 = @user.name


ul.nav.justify-content-end
  - if current_user.id == @user.id
    li.nav-item
      = link_to( "新規フォルダ", new_folder_path, class: "btn btn-success nav-link")

table.table.table-hover
  thead
    tr
      th フォルダ名

  tbody
    - @folders.each do |folder|
      tr
        td = link_to folder.name, folder

app/views/users/top.html.slim
h1 1day_100lines

- if logged_in?
  = link_to "コードを記録", user_path(id: current_user.id), class: "btn btn-primary"
- unless @chart.nil?
  = high_chart "my_chart", @chart